namespace: "softasap"
name: "gitlab_unix_builder"
description: Installs tools necessary to build average project
version: "0.0.1"
readme: "Readme.md"
authors:
    - "Vyacheslav Voronenko"
dependencies:
license:
    - "MIT"
tags:
    - softasap
repository: "https://github.com/oops-to-devops/gitlab_unix_builder"
documentation: "https://github.com/oops-to-devops/gitlab_unix_builder/blob/master/README.md"
homepage: "https://www.softasap.com"
issues: "https://github.com/orgs/oops-to-devops/projects/1"
